#!/usr/bin/env python3
"""
Parses the SpriteID enum out of sprites.hpp (as emitted by the Sprite Atlas
Workbench) and generates a parallel name table indexed the same way as the
enum itself. Run this any time sprites.hpp changes, it never needs manual
edits, no matter how many sprites exist.

Usage: gen_sprite_names.py <path to sprites.hpp> <path to output header>
"""
import re
import sys


def main():
    if len(sys.argv) != 3:
        raise SystemExit("Usage: gen_sprite_names.py <sprites.hpp> <sprite_names.hpp>")

    src_path, out_path = sys.argv[1], sys.argv[2]

    with open(src_path) as f:
        text = f.read()

    match = re.search(r"enum\s+class\s+SpriteID[^{]*\{(.*?)\};", text, re.DOTALL)
    if not match:
        raise SystemExit(f"Could not find 'enum class SpriteID {{ ... }}' in {src_path}")

    names = []
    for raw in match.group(1).split(","):
        name = raw.strip()
        if not name or name == "COUNT":
            continue
        names.append(name)

    with open(out_path, "w") as f:
        f.write("// AUTO-GENERATED by tools/gen_sprite_names.py - do not edit by hand.\n")
        f.write(f"// Source: {src_path} ({len(names)} sprites)\n")
        f.write("#pragma once\n\n")
        f.write("namespace game::sprites {\n\n")
        f.write("// Indexed identically to SpriteID - NAMES[(size_t)SpriteID::X] == \"X\"\n")
        f.write("inline constexpr const char* NAMES[] = {\n")
        for name in names:
            f.write(f'    "{name}",\n')
        f.write("};\n\n")
        f.write("}\n")

    print(f"Wrote {len(names)} sprite names to {out_path}")


if __name__ == "__main__":
    main()